import './globals.css'
import './fanta.css'
import Head from './head'

export const metadata = {
  title: 'MARKDOWN NOTES | Easy Note Taking',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <body>
        <div className="app" id="app">
          {children}
        </div>
        <div className="portal" id="portal"></div>
      </body>
    </html>
  )
}
